version: '3.3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - pg_volume:/var/lib/postgresql/data

volumes:
  pg_volume:
